### ISSUE TITLE
The `kb` unit is used instead of `kB` or `KiB` with a capital B

### ISSUE THREAD

**Issue by Flimm** [jonathan-fielding/performancebudget.io#15]
The website performancebudget.io seems to use the unit `kb`. For example: `78 kb`.

Lower-case `b` stands for a bit, while uppercase `B` stands for a byte, which is equal to eight bits. For example, `1 MBps` is eight times faster than `1 Mbps`. Generally, the bit unit is only used for Internet speeds. The size of files, of downloads of memory usually is measured in bytes, which is why I am surprised that the lowercase `b` was used here.

(Of course, there is also the confusion of whether `1 kB` is 1000 bytes or 1024 bytes, but I'll leave that to Wikipedia https://en.wikipedia.org/wiki/Kilobyte )

**Comment by jonathan-fielding** [comment]
Good spot, I fixed it in new version
